<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Recommendation Systems

---

<h1>Lesson Guide<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Recommendation-Systems" data-toc-modified-id="Recommendation-Systems-1">Recommendation Systems</a></span><ul class="toc-item"><li><span><a href="#Learning-Objectives" data-toc-modified-id="Learning-Objectives-1.1">Learning Objectives</a></span></li><li><span><a href="#Users-and-items" data-toc-modified-id="Users-and-items-1.2">Users and items</a></span></li><li><span><a href="#Get-the-data" data-toc-modified-id="Get-the-data-1.3">Get the data</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Create-two-columns-containing-date-and-year-of-the-given--rating" data-toc-modified-id="Create-two-columns-containing-date-and-year-of-the-given--rating-1.3.0.1">Create two columns containing date and year of the given  rating</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.2">Solution (double click)</a></span></li><li><span><a href="#Describe-the-rating-data" data-toc-modified-id="Describe-the-rating-data-1.3.0.3">Describe the rating data</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.4">Solution (double click)</a></span></li><li><span><a href="#How-many-ratings-have-been-given-in-each-month-and-year?" data-toc-modified-id="How-many-ratings-have-been-given-in-each-month-and-year?-1.3.0.5">How many ratings have been given in each month and year?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.6">Solution (double click)</a></span></li><li><span><a href="#How-many-different-films-have-been-rated-by-how-many-different-users?" data-toc-modified-id="How-many-different-films-have-been-rated-by-how-many-different-users?-1.3.0.7">How many different films have been rated by how many different users?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.8">Solution (double click)</a></span></li><li><span><a href="#Which-rating-scale-has-been-used?-How-many-times-has-each-rating-been-given?" data-toc-modified-id="Which-rating-scale-has-been-used?-How-many-times-has-each-rating-been-given?-1.3.0.9">Which rating scale has been used? How many times has each rating been given?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.10">Solution (double click)</a></span></li><li><span><a href="#How-many-ratings-were-given-by-each-user?" data-toc-modified-id="How-many-ratings-were-given-by-each-user?-1.3.0.11">How many ratings were given by each user?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.12">Solution (double click)</a></span></li><li><span><a href="#How-many-ratings-were-received-by-each-film?" data-toc-modified-id="How-many-ratings-were-received-by-each-film?-1.3.0.13">How many ratings were received by each film?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.3.0.14">Solution (double click)</a></span></li></ul></li></ul></li><li><span><a href="#Evaluation" data-toc-modified-id="Evaluation-1.4">Evaluation</a></span><ul class="toc-item"><li><span><a href="#MAE-and-MSE" data-toc-modified-id="MAE-and-MSE-1.4.1">MAE and MSE</a></span></li><li><span><a href="#Correlations" data-toc-modified-id="Correlations-1.4.2">Correlations</a></span></li><li><span><a href="#Precision@k-and-recall@k" data-toc-modified-id="Precision@k-and-recall@k-1.4.3">Precision@k and recall@k</a></span></li></ul></li><li><span><a href="#Baseline-prediction" data-toc-modified-id="Baseline-prediction-1.5">Baseline prediction</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Example" data-toc-modified-id="Example-1.5.0.1">Example</a></span></li><li><span><a href="#Determine-the-baseline-estimate-for-each-user-item-pair" data-toc-modified-id="Determine-the-baseline-estimate-for-each-user-item-pair-1.5.0.2">Determine the baseline estimate for each user-item pair</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.0.3">Solution (double click)</a></span></li><li><span><a href="#Is-there-any-problem-with-determining-the-baseline-like-this?" data-toc-modified-id="Is-there-any-problem-with-determining-the-baseline-like-this?-1.5.0.4">Is there any problem with determining the baseline like this?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.0.5">Solution (double click)</a></span></li></ul></li><li><span><a href="#User-item-matrix" data-toc-modified-id="User-item-matrix-1.5.1">User-item matrix</a></span><ul class="toc-item"><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.1.1">Solution (double click)</a></span></li><li><span><a href="#Evaluate-the-baseline-prediction-against-the-true-values" data-toc-modified-id="Evaluate-the-baseline-prediction-against-the-true-values-1.5.1.2">Evaluate the baseline prediction against the true values</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.1.3">Solution (double click)</a></span></li><li><span><a href="#Form-recommendation-lists-by-proposing-to-each-user-the-five-films-ranked-highest-according-to-their-baseline." data-toc-modified-id="Form-recommendation-lists-by-proposing-to-each-user-the-five-films-ranked-highest-according-to-their-baseline.-1.5.1.4">Form recommendation lists by proposing to each user the five films ranked highest according to their baseline.</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.1.5">Solution (double click)</a></span></li></ul></li><li><span><a href="#Slope-one-predictor" data-toc-modified-id="Slope-one-predictor-1.5.2">Slope-one predictor</a></span><ul class="toc-item"><li><span><a href="#Example" data-toc-modified-id="Example-1.5.2.1">Example</a></span></li><li><span><a href="#According-to-this-model,-how-would-user-8-rate-film-1?" data-toc-modified-id="According-to-this-model,-how-would-user-8-rate-film-1?-1.5.2.2">According to this model, how would user 8 rate film 1?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.5.2.3">Solution (double click)</a></span></li></ul></li></ul></li><li><span><a href="#Measuring-(dis-)similarity-between-ratings" data-toc-modified-id="Measuring-(dis-)similarity-between-ratings-1.6">Measuring (dis-)similarity between ratings</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Determine-the-pairwise-distances-between-items" data-toc-modified-id="Determine-the-pairwise-distances-between-items-1.6.0.1">Determine the pairwise distances between items</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.6.0.2">Solution (double click)</a></span></li><li><span><a href="#Based-on-the-user-cosine-similarity,-determine-who-are-the-three-closest-users-to-user-8" data-toc-modified-id="Based-on-the-user-cosine-similarity,-determine-who-are-the-three-closest-users-to-user-8-1.6.0.3">Based on the user-cosine similarity, determine who are the three closest users to user 8</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.6.0.4">Solution (double click)</a></span></li></ul></li><li><span><a href="#KNN-with-means" data-toc-modified-id="KNN-with-means-1.6.1">KNN with means</a></span><ul class="toc-item"><li><span><a href="#Example" data-toc-modified-id="Example-1.6.1.1">Example</a></span></li><li><span><a href="#What-would-we-predict-for-the-rating-given-by-user-8-for-film-1-with-this-model-with-$k=3$-and-using-cosine-similarity?" data-toc-modified-id="What-would-we-predict-for-the-rating-given-by-user-8-for-film-1-with-this-model-with-$k=3$-and-using-cosine-similarity?-1.6.1.2">What would we predict for the rating given by user 8 for film 1 with this model with $k=3$ and using cosine similarity?</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.6.1.3">Solution (double click)</a></span></li></ul></li><li><span><a href="#Singular-Value-decomposition" data-toc-modified-id="Singular-Value-decomposition-1.6.2">Singular Value decomposition</a></span><ul class="toc-item"><li><span><a href="#Evaluate-the-predictions-using-MSE,-MAE,-Pearson-and-Spearman-correlations" data-toc-modified-id="Evaluate-the-predictions-using-MSE,-MAE,-Pearson-and-Spearman-correlations-1.6.2.1">Evaluate the predictions using MSE, MAE, Pearson and Spearman correlations</a></span></li><li><span><a href="#Solution-(double-click)" data-toc-modified-id="Solution-(double-click)-1.6.2.2">Solution (double click)</a></span></li></ul></li></ul></li><li><span><a href="#Conclusions" data-toc-modified-id="Conclusions-1.7">Conclusions</a></span></li></ul></li></ul></div>

## Learning Objectives

- Understand what data is needed to form recommendations
- Learn how to evaluate a recommendation model
- Meet the main types of recommendation models

When we try to recommend items to users, we face a few fundamental problems:

1. Data Sparsity
    - There are lots of products to recommend to many users. 
    - It is unlikely that a user will ever try out a large fraction of products.
    - A few items are demanded by many users, but many only by a few.
   
- Cold Start
    - We need to be able to give recommendations to users about which we only have scarse data (if at all).
    
- Accurate, but also diverse predictions
    - We want to give useful recommendations in the sense that they match the user's preferences, but also that the recommendation contains some novelty for the user. 

- Evaluation
    - Evaluation is difficult and might differ from algorithm to algorithm.

- Scalability
    - We need to be able to give recommendations on the spot even though there might be millions of users and items which we have to analyze carefully.

- User interface
    - Users want to know why they get particular recommendations.

- Vulnerability to attacks
    - We do not want our recommendation system to be abused for promoting or inhibiting particular items.
 
- Temporal resolution
    - Tastes and preferences do not remain the same over time. The algorithms that we will see neglect any kind of dynamics.

## Users and items

In general we speak of users and items.

> **Users:** indicate preferences for products through explicit/implicit ratings

> **Items:** products which should be recommended and which have received ratings

In most cases we are going to predict a certain rating for each possible pair of user and item. If the user already gave some rating we can compare it to our prediction:

- True rating: $r_{ui}$
- Predicted rating: $\hat{r}_{ui}$

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sns.set(font_scale=1.5)
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

## Get the data

First we will need some data. Download the Movielens 100K dataset from [here](https://grouplens.org/datasets/movielens/). 
It is a very famous dataset about movie ratings. Adjust the paths to the files as necessary.

In [2]:
with open('/Users/crahmede/.surprise_data/ml-100k/ml-100k/README', 'r') as f:
    print(f.read())

SUMMARY & USAGE LICENSE

MovieLens data sets were collected by the GroupLens Research Project
at the University of Minnesota.
 
This data set consists of:
	* 100,000 ratings (1-5) from 943 users on 1682 movies. 
	* Each user has rated at least 20 movies. 
        * Simple demographic info for the users (age, gender, occupation, zip)

The data was collected through the MovieLens web site
(movielens.umn.edu) during the seven-month period from September 19th, 
1997 through April 22nd, 1998. This data has been cleaned up - users
who had less than 20 ratings or did not have complete demographic
information were removed from this data set. Detailed descriptions of
the data file can be found at the end of this file.

Neither the University of Minnesota nor any of the researchers
involved can guarantee the correctness of the data, its suitability
for any particular purpose, or the validity of results based on the
use of the data set.  The data set may be used for any research
purposes under th

In [3]:
df = pd.read_csv('/Users/crahmede/.surprise_data/ml-100k/ml-100k/u.data', 
                 header=None, 
                 sep='\t', 
                 names=['user_id', 'item_id', 'rating', 'timestamp'])
df['date'] = pd.to_datetime(df['timestamp'], unit='s')



In [4]:
df.head()

user_id  item_id  rating  timestamp                date
0      196      242       3  881250949 1997-12-04 15:55:49
1      186      302       3  891717742 1998-04-04 19:22:22
2       22      377       1  878887116 1997-11-07 07:18:36
3      244       51       2  880606923 1997-11-27 05:02:03
4      166      346       1  886397596 1998-02-02 05:33:16

In [5]:
df.user_id.min(), df.item_id.min()

(1, 1)

To work better with python indices, we adjust the id labels so that they start at 0.

In [6]:
df['user_id'] = df['user_id'] - 1
df['item_id'] = df['item_id'] - 1

#### Create two columns containing date and year of the given  rating 

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
df['year'] = df.date.dt.year
df['month'] = df.date.dt.month
</span>

#### Describe the rating data

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
df.describe()
</span>

#### How many ratings have been given in each month and year?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
df.groupby(['year', 'month'], sort=True)[['date']].count().plot(kind='barh')
plt.show()
</span>

#### How many different films have been rated by how many different users?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
print(df.user_id.unique().shape)
print(df.item_id.unique().shape)
</span>

#### Which rating scale has been used? How many times has each rating been given?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
print(np.sort(df.rating.unique()))
df.rating.value_counts(sort=False, normalize=True).plot(kind='bar')
plt.xticks(rotation=0)
plt.xlabel('rating')
plt.show()
</span>

#### How many ratings were given by each user?

- Determine the user with the highest number of ratings.
- Plot a histogram with the rating count per user distribution.

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
print(df.groupby('user_id')['rating'].count().argmax())
print(df.groupby('user_id')['rating'].count().max())
df.groupby('user_id')['rating'].count().hist()
plt.yscale('log')
plt.show()
</span>

#### How many ratings were received by each film?

- Determine the film with the highest number of ratings.
- Plot a histogram with the rating count per film distribution.

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
print(df.groupby('item_id')['rating'].count().argmax())
print(df.groupby('item_id')['rating'].count().max())
df.groupby('item_id')['rating'].count().hist()
plt.yscale('log')
plt.show()
</span>

## Evaluation

### MAE and MSE

We can compare all existing ratings to our prediction for example using the root mean squared error (RMSE) or the mean absolute error (MAE):

    
$$
\begin{eqnarray*}
{\rm MAE} &=& \frac{1}{|R|}\sum_{(u,i)\in R}|r_{ui}-{\tilde r}_{ui}|\\
{\rm RMSE} &=& \left(\frac{1}{|R|}\sum_{(u,i)\in R}(r_{ui}-{\tilde r}_{ui})^2\right)^{1/2}
\end{eqnarray*}
$$

Here, $R$ stands for the set of all user-item pairs. $|\cdot|$ indicates the cardinality of the set (here the number of user-item pairs).

### Correlations

Alternatively one can use correlations between true and predicted values for model evaluation, e.g.

- the Pearson correlation
- the Spearman rank correlation
- Kendall's tau

You can call these three for example with panda's `.corr()` function by setting the `method` argument.
    
The above scores are alright to obtain a model assessment if we have explicit ratings, but in the case of implicit ratings we might only be able to rank the items. In general, we would like to recommend the top-ranked items, but we have to evaluate if the top-ranked ones are really the ones relevant to the user, or if for some irrelevant items we predicted higher ratings.
In that regard, we can use the usual classification metrics.

### Precision@k and recall@k

Often users will not really care about all the rating predictions we are making, but instead they will have a major interest only in a few top-ranked items, let's say the $k$ top-ranked items. So it is appropriate to take only these $k$ ratings into account. We then ask how many of these $k$ items are relevant to the user. The relevance is in general difficult to measure, but we can for example ask how many out of the $k$ top-ranked items have a score beyond a certain threshold.

We can then define the so-called precision@k and recall@k for $k$ recommended items:

$$
\begin{eqnarray*}
{\rm precision@k} &=& \frac{\rm  Recommended\ items\ that\ are\ relevant}{\rm Recommended\ items}\\
\\
{\rm recall@k} &=& 
\frac{\rm  Recommended\ items\ that\ are\ relevant}{\rm Relevant\ items}
\end{eqnarray*}
$$

Out of these scores we can define an F1@k score in the usual way.

## Baseline prediction

As we are predicting ratings $\hat{r}_{ui}$ of user $u$ on item $i$, the baseline should be the mean of all ratings, $\mu$.

As we will always be considering a specific user or a specific item, we can determine how much each user's or item's ratings are above the average. 

Therefore we add a bias term $b_u$ for each user and $b_i$ for each item, so that our baseline is

$$
{\rm baseline}_{ui} = \mu + b_u + b_i
$$

#### Example

Let's say for example that the average rating is $\mu=3.52$. Our user is very enthusiastic and on average evaluates items better than the average user by $b_u=0.3$. The item is very popular receiving above average ratings with $b_i=0.5$. So we would have a baseline prediction of $4.32$.

We will look at various models which make more accurate predictions based on either similarity or content.

#### Determine the baseline estimate for each user-item pair

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
mu = df.rating.mean()
print(mu)
bu = df.groupby('user_id')[['rating']].mean() - mu
print(bu.head())
bi = df.groupby('item_id')[['rating']].mean() - mu
print(bi.head())
baseline = mu + bu.values.reshape(-1, 1) + bi.values.reshape(1, -1)
print(baseline)
</span>

#### Is there any problem with determining the baseline like this? 

- Check the range of the baseline ratings.
- How would you adjust that?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
print(baseline.argmax(), baseline.max())
print(baseline.min())
print(int(baseline.argmax() / baseline.shape[1]))
print(baseline.argmax() % baseline.shape[1])
print(baseline[848, 813])
baseline[baseline>5] = 5
baseline[baseline<1] = 1
print(baseline.max(), baseline.min())
plt.hist(baseline.ravel())
plt.show()
</span>

### User-item matrix

We can construct the user-item matrix by reading all user-item-rating triples into a scipy-sparse matrix. Recall how that would work for any matrix. How would you apply this procedure to the given ratings?

In [7]:
from scipy import sparse

In [8]:
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = sparse.csr_matrix((data, (row, col)), shape=(3, 3))
A

<3x3 sparse matrix of type '<class 'numpy.longlong'>'
	with 6 stored elements in Compressed Sparse Row format>

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
df.user_id.unique().shape
row = df.user_id
col = df.item_id
data = df.rating
rui = sparse.csr_matrix((data, (row, col)), shape=(df.user_id.unique().shape[0], df.item_id.unique().shape[0]))
rui
</span>

#### Evaluate the baseline prediction against the true values

Evaluate using 
- the MSE
- the MAE
- the Pearson correlation
- the Spearman correlation

In [9]:
from scipy.stats import pearsonr, spearmanr

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
rui_flat = rui.toarray().ravel()
residuals = (rui_flat-baseline.ravel())[rui_flat>0]
print(np.mean(np.square(residuals)))
print(np.mean(np.abs(residuals)))
print(pearsonr(rui_flat[rui_flat>0], baseline.ravel()[rui_flat>0])[0])
print(spearmanr(rui_flat[rui_flat>0], baseline.ravel()[rui_flat>0])[0])
</span>

#### Form recommendation lists by proposing to each user the five films ranked highest according to their baseline. 

Calculate the fraction of all the films which are ever proposed in any of these lists. This fraction is called the **coverage**. Most recommender systems would make sure to increase this coverage. Are you proposing films which have been rated very frequently?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
baseline_recommendation = []
for i in range(len(baseline)):
    baseline_recommendation.append(sorted(list(zip(range((baseline.shape[1])), baseline[i])), key=lambda x: x[1], reverse=True)[:5])
baseline_recommendation = np.array(baseline_recommendation)
print(baseline_recommendation[0:, :, 0])
baseline_recommendation_unique = np.unique(baseline_recommendation[0:, :, 0].ravel()).astype(int)
print(baseline_recommendation_unique)
print(df.groupby('item_id')['rating'].count().loc[baseline_recommendation_unique])
</span>

### Slope-one predictor


This scheme makes use of both the information from other users who rated the same item and from the other items rated by the same user to predict a rating:

$$
\hat{r}_{ui} = \mu_u + \frac{1}{|R_i(u)|}\sum_{j \in R_i(u)}{\rm dev}(i,j)
$$

where $R_i(u)$ is the set of items rated by user $u$
and the average difference between the ratings of item $i$ and $j$ is

$$
{\rm dev}(i,j) = \frac{1}{|U_{ij}|}\sum_{u\in U_{ij}}(r_{ui}-r_{uj})
$$

and $U_{ij}$ is the set of all users that have rated both items $i$ and $j$.

#### Example

Consider the following example of ratings

|   -     | item 1 | item 2|
| ------- |:------:| -----:|
| user 1  | 2      | 1.8   |
| user 2  | 1      |  ?    |

Then we have

$\mu_{\rm user 2}=1$, $|U_{12}|=1$, $r_{11}=2$, $r_{12}=1.8$ and

$$
r_{22} = 1+\frac{1}{1}(1.8-2) = 0.8
$$ 

#### According to this model, how would user 8 rate film 1?

In [10]:
mu_user_8 = df[df.user_id==8].rating.mean()
mu_user_8

4.2727272727272725

In [11]:
rated_by_user_8 = df[df.user_id==8]['item_id'].values
rated_by_user_8

array([297, 690, 520, 486, 285,   5, 478, 339, 526, 506, 275, 614, 689,
       293, 482, 401, 370, 241, 200,  49,   6, 384])

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
rui_np = rui.toarray()
def slope_one_predictor(user_predict, item_predict, rui_np):
    rated_by_user = np.arange(rui_np.shape[1])[rui_np[user_predict]>0]
    user_mean = (rui_np[user_predict][rui_np[user_predict]>0]).mean()
    deviance = 0
    for item in rated_by_user:
        deviance_current = rui_np[((rui_np[:, item_predict]>0) & (rui_np[:, item]>0))]
        deviance_current = (deviance_current[:, item_predict] - deviance_current[:, item]).sum() / deviance_current.shape[0]
        deviance += deviance_current
    deviance = deviance / len(rated_by_user)
    deviance += user_mean
    return deviance
slope_one_predictor(8, 1, rui.toarray())
</span>

## Measuring (dis-)similarity between ratings

We use similarity measures to infer from past ratings what to recommend in the future. This can be 

- **item based:** a user who already rated some items positively would like to have similar items recommended in the future
- **user based:** users who agree on their item ratings will do so also in the future

We can use similarity measures we have already seen frequently:

- **Correlation similarity:** 

$$
{\rm sim}_{\rm corr}(u,v) = \frac{(u-\bar{u})\cdot (v-\bar{v})}{\|u\|\|v\|}
$$

- **Cosine similarity**

$$
{\rm sim}_{\cos}(u,v) = \frac{u\cdot v}{\|u\|\|v\|}
$$

- **Mean squared difference**

$$
{\rm msd}(u,v) = \frac{1}{|I_{uv}|}\sum_{i\in I_{uv}}(r_{ui}-r_{vi})^2
$$

and then

$$
{\rm msd\_sim}(u,v) = \frac{1}{{\rm msd}(u,v)+1} 
$$

and similarly for item pairs $i,j$. $|I_{uv}|$ is the number of items rated by both users $u$ and $v$.

There exist many more based on the usual distance metrics, but also many specialized for recommendation system requirements.

In [12]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity, pairwise_distances, euclidean_distances

In [13]:
row = df.user_id
col = df.item_id
data = df.rating
rui = sparse.csr_matrix((data, (row, col)), shape=(df.user_id.unique().shape[0], df.item_id.unique().shape[0]))
rui

<943x1682 sparse matrix of type '<class 'numpy.longlong'>'
	with 100000 stored elements in Compressed Sparse Row format>

In [14]:
user_similarity_cos = cosine_similarity(rui)
user_similarity_cos[0, :10]

array([1.        , 0.16693098, 0.04745954, 0.06435782, 0.37847518,
       0.43023944, 0.4403668 , 0.31907211, 0.07813837, 0.37654381])

In [15]:
user_distance_cos = cosine_distances(rui)
user_distance_cos[0, :10]

array([0.        , 0.83306902, 0.95254046, 0.93564218, 0.62152482,
       0.56976056, 0.5596332 , 0.68092789, 0.92186163, 0.62345619])

In [16]:
user_distance_corr = pairwise_distances(rui.toarray(), metric='correlation')
user_distance_corr[0, :10]

array([0.        , 0.89367807, 1.01642393, 0.97828412, 0.69740786,
       0.65402415, 0.67998316, 0.7237923 , 0.96118849, 0.71150891])

In [17]:
def msd(x, y):
    """
    check for items rated by both users,
    then calculate Euclidean distance between users
    """
    condition = (x!=0) & (y!=0)
    try:
        x_c = x[condition].reshape(1, -1)
        y_c = y[condition].reshape(1, -1)
        e = (euclidean_distances(x_c, y_c)[0, 0])**2 / condition.sum()
        return 1 - 1 / (1 + e)
    except:
        return 1

In [18]:
user_distance_msd = pairwise_distances(rui.toarray(), metric=msd)
user_distance_msd[0, :10]

array([0.        , 0.6       , 0.76470588, 0.73076923, 0.64912281,
       0.62790698, 0.66512702, 0.46031746, 0.5       , 0.53892216])

#### Determine the pairwise distances between items

Hint: Calculate the same as above for the transposed user-item matrix.

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
item_distance_cos = cosine_distances(rui.T)
print(item_distance_cos[0, :10])
item_distance_corr = pairwise_distances(rui.T.toarray(), metric='correlation')
print(item_distance_corr[0, :10])
item_distance_msd = pairwise_distances(rui.T.toarray(), metric=msd)
print(item_distance_msd[0, :10])
</span>

#### Based on the user-cosine similarity, determine who are the three closest users to user 8

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
sorted(zip(np.arange(user_similarity_cos.shape[0]), user_similarity_cos[8]), 
       key=lambda x: x[1], reverse=True)[:4]
</span>

### KNN with means

In the kNN with means model, we look at either the $k$ most similar users or items and predict based on

- user similarity:

$$
\hat{r}_{ui} = \mu_u+\frac{\sum_{v \in N_i^k(u)}{\rm sim}(u,v)(r_{vi}-\mu_v)}{\sum_{v \in N_i^k(u)}{\rm sim}(u,v)}
$$

- item similarity:


$$
\hat{r}_{ui} = \mu_i+\frac{\sum_{j \in N_u^k(i)}{\rm sim}(i,j)(r_{uj}-\mu_j)}{\sum_{j \in N_u^k(i)}{\rm sim}(i,j)}
$$

Here $N_i^k(u)$ denotes the $k$ most similar users to user $u$ who rated item $i$.

#### Example

As an example, let's take user similarity (e.g. correlation similarity) and we consider the two nearest neighbors of user $1$.

Let's say we have 

$\mu_1 = 3$, $\mu_2 = 2$, $\mu_3 = 4$,
${\rm sim}(1,2)=0.8$, ${\rm sim}(1,3)=0.5$, 

and want to predict for item $1$ with 

$r_{21}=3.2$ and $r_{31}=3.8$.

Then we obtain

$$
r_{11} = 3 +\frac{0.8(3.2-2)+0.5(3.8-4)}{0.8+0.5}
= 3+\frac{0.8\cdot1.2+0.5\cdot(-0.2)}{1.3}
\approx 3.66
$$

#### What would we predict for the rating given by user 8 for film 1 with this model with $k=3$ and using cosine similarity?

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
def k_with_means(user_predict, item_predict, rui_np, similarities, k=3):
    user_mean = (rui_np[user_predict][rui_np[user_predict]>0]).mean()   
    users_who_rated = np.arange(rui_np.shape[0])[rui_np[:, item_predict]>0]
    user_similarities = similarities[user_predict][rui_np[:, item_predict]>0]
    most_similar_users = sorted(list(zip(users_who_rated, user_similarities)), 
                            key=lambda x: x[1], reverse=True)[:k]
    similarities = np.array([sim for user, sim in most_similar_users ])
    user_deviations = []
    for user, sim in most_similar_users:
        r_vi = rui_np[user, item_predict]
        user_mean_v = (rui_np[user][rui_np[user]>0]).mean()
        user_deviations.append(r_vi - user_mean_v)        
    user_deviations = np.array(user_deviations)
    prediction = user_mean + np.dot(similarities, user_deviations)/similarities.sum()    
    return prediction
k_with_means(10, 1, rui_np, user_similarity_cos)
</span>

### Singular Value decomposition

Singular value decomposition is related to principal component analysis. It makes use of the spectral theorem that every matrix $X$ of shape $n\times p$ can be written as a dot product of three matrices

$$
X = U \Sigma V^T
$$

where $U$ is of shape $n\times n$, $V$ is of shape $p\times p$ and $\Sigma$ of shape $n\times p$ is a diagonal matrix with the so-called singular values on its diagonal (which are simply the square roots of the eigenvalues of $X^T X$). Both $U$ and $V$ are orthogonal matrices (which means their inverse is their transpose).

In the same way as for principal component analysis, we can reduce the dimensionality by restricting to the components with the $K$ largest singular values.

This is what we are going to do with the user-item matrix. As it is very sparse anyway, we can expect that we won't loose too much information in this way and that we will somehow extract the main tastes and item attributes in this way.

That is whereas the rating matrix can be exactly written as

$$
R = U\Sigma V^T
$$

we can approximate it by choosing $\Sigma$ of shape $K\times K$ where $K<{\rm min}(n,p)$ as

$$
\hat{R} = U\Sigma_K V^T
$$

Not restricting $K$ will lead to perfect predictions on the training set.
    

In [19]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=400)
rui_transformed = svd.fit_transform(rui)
rui_transformed

array([[ 4.21564507e+01,  1.46291293e+00, -1.33595403e+00, ...,
         2.40035622e-01,  2.19761720e-01,  6.43634360e-01],
       [ 8.98235172e+00, -1.14157452e+01,  1.14540401e+01, ...,
        -7.94876790e-01, -1.37208950e+00, -4.64055187e-01],
       [ 3.62469291e+00, -6.27232708e+00,  5.08928630e+00, ...,
         1.35355500e-01,  8.76252607e-02, -2.02693442e-01],
       ...,
       [ 4.76921060e+00, -6.12612044e+00,  1.34309272e+00, ...,
         4.25552191e-02, -7.35491683e-03, -2.42807964e-01],
       [ 1.53951858e+01,  1.98222287e+00,  4.98592430e+00, ...,
        -9.33711489e-01,  3.43300619e-01,  3.91089695e-01],
       [ 2.70617041e+01, -2.67536312e+00, -1.27540348e+01, ...,
        -1.68608473e+00, -1.17968492e+00, -1.45224707e+00]])

In [20]:
rui_predicted = svd.inverse_transform(rui_transformed)
rui_predicted

array([[ 4.95859054e+00,  2.94829939e+00,  3.70979041e+00, ...,
         8.52650385e-03, -9.93049309e-03,  4.32643872e-02],
       [ 3.93374988e+00,  3.44893657e-01,  4.62819467e-01, ...,
        -1.93306899e-02, -4.07867629e-02,  4.41300631e-04],
       [-6.42163525e-03, -2.12489040e-01, -5.68957579e-02, ...,
         5.90014380e-02,  2.99654415e-02, -4.08978613e-03],
       ...,
       [ 4.96101511e+00, -3.08578350e-01, -1.90203613e-01, ...,
         4.46497012e-04,  4.13624175e-02, -1.52370097e-02],
       [-1.45304123e-01,  3.72512344e-01,  7.23479756e-02, ...,
        -4.98603834e-02, -2.90245048e-03,  7.86873694e-03],
       [-2.81577568e-02,  4.58021739e+00, -8.32127789e-03, ...,
         4.11476481e-02,  9.88231466e-02, -2.71771790e-02]])

In [21]:
rui_predicted.shape

(943, 1682)

#### Evaluate the predictions using MSE, MAE, Pearson and Spearman correlations

#### Solution (double click)

<span style="color:white;font-family:'Courier New'"><br/>
residuals_svd = (rui_flat-rui_predicted.ravel())[rui_flat>0]
print(np.mean(np.square(residuals_svd)))
print(np.mean(np.abs(residuals_svd)))
print(pearsonr(rui_flat[rui_flat>0], rui_predicted.ravel()[rui_flat>0])[0])
print(spearmanr(rui_flat[rui_flat>0], rui_predicted.ravel()[rui_flat>0])[0])
</span>

## Conclusions


There are many more recommendation system models, but with these simple models one can already reach quite far. What is still lacking is to establish an efficient implementation that allows us to cross-validate our predictions.