<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Linear algebra practice

---

In [1]:
import numpy as np

#### 1. Transform the following two vectors into numpy arrays.

In [2]:
vec_1 = [2, 4, 1]
vec_2 = [1, 3, 0]

In [27]:
vec_1 = np.array(vec_1)
vec_2 = np.array(vec_2)
vec_1.shape

(3,)

#### 2. For the two vectors, calculate
    
- $3 \cdot {\rm vec}_1 + 2\cdot {\rm vec}_2$
- $-0.5\cdot {\rm vec}_1 + 3\cdot {\rm vec}_2$ 
- the scalar product 
- the magnitude of each vector

In [11]:
one = (3*vec_1) + (2*vec_2)
print(one)
two = (-.5*vec_1) + (3*vec_2)
print(two)
three = np.dot(vec_1,vec_2)
print(three)
four_a = np.linalg.norm(vec_1)
print(four_a)
four_b = np.linalg.norm(vec_2)
print(four_b)

[ 8 18  3]
[ 2.   7.  -0.5]
14
4.58257569495584
3.1622776601683795


#### 3. Transform the following lists into numpy matrices.

In [12]:
A = [[2,1],[-2,3]]
B = [[1,3,4],[0,1,2],[1,0,0]]
C = [[2,3,0],[0,1,4],[1,0,1]]

In [15]:
A = np.array(A)
B = np.array(B)
C = np.array(C)
A

array([[ 2,  1],
       [-2,  3]])

#### 4. Extract the row and column vectors from A.

In [70]:
row1 = A[0,:]
row2 = A[1,:]
col1 = A[:,0]
col2 = A[:,1]

row1

array([2, 1])

#### 5. Form the matrix products $B\cdot C$ and $C\cdot B$. Compare!

In [25]:
B.dot(C)

array([[ 6,  6, 16],
       [ 2,  1,  6],
       [ 2,  3,  0]])

In [26]:
C.dot(B)

array([[ 2,  9, 14],
       [ 4,  1,  2],
       [ 2,  3,  4]])

#### 6. Form the dot products $B\cdot {\rm vec}_1$ and ${\rm vec}_1\cdot B$. Compare!

In [34]:
B.dot(vec_1)

array([18,  6,  2])

In [33]:
vec_1.dot(B)

array([ 3, 10, 16])

#### 7. Obtain the transpose of the matrices $A$, $B$, $C$.

In [40]:
A_trans = A.T
A_trans

array([[ 2, -2],
       [ 1,  3]])

In [41]:
B_trans = B.T
B_trans

array([[1, 0, 1],
       [3, 1, 0],
       [4, 2, 0]])

In [42]:
C_trans = C.T
C_trans

array([[2, 0, 1],
       [3, 1, 0],
       [0, 4, 1]])

#### 8. Form the matrix product $A^T \cdot A$ and $A\cdot A^T$. Compare! Repeat for the matrices $B$ and $C$. Do you notice anything special about the resulting matrices?

In [36]:
A_trans.dot(A)

array([[ 8, -4],
       [-4, 10]])

In [43]:
A.dot(A_trans)

array([[ 5, -1],
       [-1, 13]])

In [37]:
B_trans.dot(B)

array([[ 2,  3,  4],
       [ 3, 10, 14],
       [ 4, 14, 20]])

In [44]:
B.dot(B_trans)

array([[26, 11,  1],
       [11,  5,  0],
       [ 1,  0,  1]])

In [38]:
C_trans.dot(C)

array([[ 5,  6,  1],
       [ 6, 10,  4],
       [ 1,  4, 17]])

In [45]:
C.dot(C_trans)

array([[13,  3,  2],
       [ 3, 17,  4],
       [ 2,  4,  2]])

#### 9. Calculate the inverse matrices of $A$, $B$ and $C$ if possible. Check that the found matrices are indeed the inverses by taking the matrix product with the original matrices.

In [48]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)
print(A_inv)
print(B_inv)
print(C_inv)

[[ 0.375 -0.125]
 [ 0.25   0.25 ]]
[[ 0.00000000e+00  2.22044605e-16  1.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00 -1.00000000e+00]
 [-5.00000000e-01  1.50000000e+00  5.00000000e-01]]
[[ 0.07142857 -0.21428571  0.85714286]
 [ 0.28571429  0.14285714 -0.57142857]
 [-0.07142857  0.21428571  0.14285714]]


In [49]:
A_chk = A.dot(A_inv)
B_chk = B.dot(B_inv)
C_chk = C.dot(C_inv)
print(A_chk)
print(B_chk)
print(C_chk)

[[1. 0.]
 [0. 1.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  2.22044605e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00 -1.11022302e-16]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]


#### 10. Solve the system of equations

$$
\begin{eqnarray}
2\, x_1 + 1\, x_2 &=& 3\\
-2\, x_1 + 3\, x_2 &=& 1
\end{eqnarray}$$

Note that this system of equations can be written as

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)
\left(
\begin{array}{c}
x_1\\
x_2 
\end{array}
\right)
=
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

Find out how to use the command `np.linalg.solve` to solve this system of equations.

In [50]:
b = np.array([3,1])
np.linalg.solve(A,b)

array([1., 1.])

#### 11. Check that the same result can be obtained by calculating

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)^{-1}
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

In [51]:
A_inv.dot(b)

array([1., 1.])

### In the following exercises, work purely with python lists to create your own functions which do the same as the numpy functions. Verify your results with the examples from above.

#### 12. Write a function that adds two vectors to each other

In [57]:
# vec_1 = [2, 4, 1]
# vec_2 = [1, 3, 0]

def vector_add(vec1, vec2):
    vec_sum = []
    for i in range(len(vec1)):
        vec_sum.append(vec1[i] + vec2[i])
    print(vec_sum)

vector_add(vec_1, vec_2)

[3, 7, 1]


#### 13. Write a function that subtracts two vectors from each other

In [59]:
# vec_1 = [2, 4, 1]
# vec_2 = [1, 3, 0]

def vector_subtract(vec1, vec2):
    vec_sub = []
    for i in range(len(vec1)):
        vec_sub.append(vec1[i] - vec2[i])
    print(vec_sub)

vector_subtract(vec_1, vec_2)

[1, 1, 1]


#### 14. Write a function that multiplies a vector by a number

In [63]:
def vector_scalar(vec1, a):
    vec_scal = []
    for i in range(len(vec1)):
        vec_scal.append(vec1[i] * a)
    print(vec_scal)

vector_scalar(vec_1, 2)

[4, 8, 2]


#### 15. Write a function that calculates the length of a vector

In [65]:
def vector_length(vec1):
    vec_len = 0
    for i in vec1:
        vec_len += i ** 2
    vec_len = vec_len ** 0.5
    print(vec_len)

vector_length(vec_1)

4.58257569495584


#### 16. Write a function that calculates the scalar product of two vectors

In [68]:
# vec_1 = [2, 4, 1]
# vec_2 = [1, 3, 0]

def vector_vector(vec1, vec2):
    vec_vec = 0
    for i in range(len(vec1)):
        vec_vec += vec1[i] * vec2[i]
    print(vec_vec)

vector_vector(vec_1, vec_2)

14


#### 17. Write a function that returns the rows of a matrix

In [76]:
#recap of numpy method

print(A)
row1 = A[0,:]
row2 = A[1,:]
col1 = A[:,0]
col2 = A[:,1]

print(row1)
print(col1)

[[ 2  1]
 [-2  3]]
[2 1]
[ 2 -2]


In [75]:
#now do it as requested

def matrix_rows(A):
    A_rows = []
    for i in range(len(A)):
        A_rows.append(A[i])
    print(A_rows)

matrix_rows(A)

[array([2, 1]), array([-2,  3])]


#### 18. Write a function that returns the columns of a matrix

In [98]:
def matrix_cols(A):
    A_cols = []
    for j in range(len(A[0])):
        A_list = []
        for row in A:
            A_list.append(row[j])
        A_cols.append(A_list)
    print(A_cols)

matrix_cols(A)

[[2, -2], [1, 3]]


#### 19. Write a function that multiplies a matrix with a vector

In [99]:
print(A)
#print(vec_1)

[[ 2  1]
 [-2  3]]


In [95]:
vec_1 = [2, 4, 1]


def matrix_vector(A,vec1):
    mat_vec = []
    for row in A:
        mat_vec_cnt = 0
        for j in range(len(row)):
            mat_vec_cnt += row[j] * vec1[j]
        mat_vec.append(mat_vec_cnt)
    print(mat_vec)

#just quickly hardcode vec_1 to be correct size...
matrix_vector(A,vec_1[:2])

[8, 8]


In [94]:
vec_1[:2]

[2, 4]

#### 20. Write a function that multiplies a matrix with a matrix 

In [ ]:
def matrix_matrix(A,B):
    mat_mat = []
    for row in A:
        mat_vec_cnt = 0
        for j in range(len(row)):
            mat_vec_cnt += row[j] * vec1[j]
        mat_vec.append(mat_vec_cnt)
    print(mat_vec)

#just quickly hardcode vec_1 to be correct size...
matrix_vector(A,vec_1[:2])

#### 21. Write a function that returns the transpose of a given matrix